apiVersion: v1
kind: Pod
metadata:
  name: traffic
spec:
  containers:
  - name: traffic
    image: curlimages/curl
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do curl -s web > /dev/null; sleep 1; done"